"""
Secteurs et concurrents pré-configurés.
Base de connaissance métier pour le retail français.
"""

SECTORS = {
    "supermarche": {
        "name": "Grande Distribution",
        "competitors": [
            {
                "name": "Carrefour",
                "website": "https://www.carrefour.fr",
                "playstore_app_id": "com.carrefour.fid.android",
                "appstore_app_id": "378305156",
                "instagram_username": "carrefourfrance",
                "tiktok_username": "carrefourfrance",
                "youtube_channel_id": "UCfhwXXWV0MT9hbXR3SJMXjQ",
            },
            {
                "name": "Leclerc",
                "website": "https://www.e.leclerc",
                "playstore_app_id": "com.infomil.bill",
                "appstore_app_id": "756693888",
                "instagram_username": "e.leclerc",
                "tiktok_username": "e.leclerc",
            },
            {
                "name": "Auchan",
                "website": "https://www.auchan.fr",
                "playstore_app_id": "com.auchan.android",
                "appstore_app_id": "393068659",
                "instagram_username": "auchan_france",
                "tiktok_username": "auchan",
            },
            {
                "name": "Intermarché",
                "website": "https://www.intermarche.com",
                "playstore_app_id": "com.intermarche.mobile.courses",
                "appstore_app_id": "1447048498",
                "instagram_username": "intermarche",
                "tiktok_username": "intermarche",
            },
            {
                "name": "Lidl",
                "website": "https://www.lidl.fr",
                "playstore_app_id": "com.lidl.eci.lidlplus",
                "appstore_app_id": "1238611143",
                "instagram_username": "lidlfrance",
                "tiktok_username": "lidlfrance",
            },
            {
                "name": "Monoprix",
                "website": "https://www.monoprix.fr",
                "playstore_app_id": "fr.monoprix.monoprix",
                "appstore_app_id": "966459890",
                "instagram_username": "monoprix",
                "tiktok_username": "monoprix",
            },
            {
                "name": "Casino",
                "website": "https://www.casino.fr",
                "playstore_app_id": "com.casino.casino",
                "instagram_username": "groupecasino",
            },
            {
                "name": "Système U",
                "website": "https://www.magasins-u.com",
                "playstore_app_id": "com.systeme_u.courseu",
                "appstore_app_id": "1451498498",
                "instagram_username": "magasins_u",
            },
            {
                "name": "Franprix",
                "website": "https://www.franprix.fr",
                "playstore_app_id": "fr.franprix.app",
                "instagram_username": "franprix",
            },
            {
                "name": "Picard",
                "website": "https://www.picard.fr",
                "playstore_app_id": "com.picard.app",
                "appstore_app_id": "1507741802",
                "instagram_username": "piabordfrance",
            },
            {
                "name": "Grand Frais",
                "website": "https://www.grandfrais.com",
                "instagram_username": "grandfrais_officiel",
            },
            {
                "name": "Aldi",
                "website": "https://www.aldi.fr",
                "playstore_app_id": "com.aldi.mobile",
                "instagram_username": "aldi_france",
            },
        ],
    },
    "mode": {
        "name": "Mode & Habillement",
        "competitors": [
            {
                "name": "Zara",
                "website": "https://www.zara.com/fr",
                "playstore_app_id": "com.inditex.zara",
                "appstore_app_id": "547347221",
                "instagram_username": "zara",
                "tiktok_username": "zara",
            },
            {
                "name": "H&M",
                "website": "https://www.hm.com/fr",
                "playstore_app_id": "com.hm.goe",
                "appstore_app_id": "834465911",
                "instagram_username": "hm",
                "tiktok_username": "hm",
            },
            {
                "name": "Kiabi",
                "website": "https://www.kiabi.com",
                "playstore_app_id": "com.kiabi.app",
                "appstore_app_id": "495571498",
                "instagram_username": "kiabi_official",
                "tiktok_username": "kiabi_official",
            },
            {
                "name": "Primark",
                "website": "https://www.primark.com/fr",
                "instagram_username": "primark",
                "tiktok_username": "primark",
            },
            {
                "name": "Uniqlo",
                "website": "https://www.uniqlo.com/fr",
                "playstore_app_id": "com.uniqlo.fr.catalogue",
                "appstore_app_id": "1073498911",
                "instagram_username": "uniqlo",
                "tiktok_username": "uniqlo",
            },
            {
                "name": "C&A",
                "website": "https://www.c-and-a.com/fr",
                "playstore_app_id": "com.canda.app",
                "appstore_app_id": "1094498498",
                "instagram_username": "ca",
            },
            {
                "name": "Jules",
                "website": "https://www.jules.com",
                "playstore_app_id": "com.jules.app",
                "instagram_username": "jules",
            },
            {
                "name": "Celio",
                "website": "https://www.celio.com",
                "playstore_app_id": "com.celio.app",
                "instagram_username": "celio_officiel",
            },
            {
                "name": "Mango",
                "website": "https://www.mango.com/fr",
                "playstore_app_id": "com.mango.mango",
                "appstore_app_id": "377917498",
                "instagram_username": "mango",
                "tiktok_username": "mango",
            },
            {
                "name": "Bonobo",
                "website": "https://www.bonoboplanet.com",
                "instagram_username": "bonoboplanet",
            },
            {
                "name": "Pimkie",
                "website": "https://www.pimkie.fr",
                "playstore_app_id": "com.pimkie.app",
                "instagram_username": "pimkie",
            },
            {
                "name": "Camaïeu",
                "website": "https://www.camaieu.fr",
                "instagram_username": "camaieu",
            },
        ],
    },
    "beaute": {
        "name": "Beauté & Cosmétiques",
        "competitors": [
            {
                "name": "Sephora",
                "website": "https://www.sephora.fr",
                "playstore_app_id": "com.sephora.android",
                "appstore_app_id": "393328150",
                "instagram_username": "sephorafrance",
                "tiktok_username": "sephora",
            },
            {
                "name": "Nocibé",
                "website": "https://www.nocibe.fr",
                "playstore_app_id": "com.douglas.nocibe",
                "appstore_app_id": "1123649654",
                "instagram_username": "nocibe_france",
            },
            {
                "name": "Yves Rocher",
                "website": "https://www.yves-rocher.fr",
                "playstore_app_id": "com.yvesrocher.yvesrocher",
                "instagram_username": "yvesrocherusa",
                "tiktok_username": "yvesrocher",
            },
            {
                "name": "Marionnaud",
                "website": "https://www.marionnaud.fr",
                "playstore_app_id": "com.marionnaud.app",
                "instagram_username": "marionnaud_france",
            },
            {
                "name": "L'Occitane",
                "website": "https://www.loccitane.com/fr",
                "playstore_app_id": "com.loccitane.android",
                "appstore_app_id": "603378498",
                "instagram_username": "loccitane",
                "tiktok_username": "loccitane",
            },
            {
                "name": "Rituals",
                "website": "https://www.rituals.com/fr-fr",
                "playstore_app_id": "com.rituals.app",
                "appstore_app_id": "1147919307",
                "instagram_username": "rituals",
                "tiktok_username": "rituals",
            },
            {
                "name": "Kiko Milano",
                "website": "https://www.kikocosmetics.com/fr-fr",
                "playstore_app_id": "com.kiko.app",
                "appstore_app_id": "960498498",
                "instagram_username": "kilocosmetics",
                "tiktok_username": "kikocosmetics",
            },
            {
                "name": "Lush",
                "website": "https://www.lush.com/fr",
                "playstore_app_id": "com.lush.lushcosmetics",
                "instagram_username": "laboratlush",
                "tiktok_username": "lush",
            },
            {
                "name": "MAC Cosmetics",
                "website": "https://www.maccosmetics.fr",
                "instagram_username": "maccosmetics",
                "tiktok_username": "maccosmetics",
            },
            {
                "name": "NYX Professional Makeup",
                "website": "https://www.nyxcosmetics.fr",
                "instagram_username": "nyxcosmetics_france",
                "tiktok_username": "nyxcosmetics",
            },
        ],
    },
    "electromenager": {
        "name": "Électroménager & High-Tech",
        "competitors": [
            {
                "name": "Darty",
                "website": "https://www.darty.com",
                "playstore_app_id": "com.darty.app",
                "appstore_app_id": "352210890",
                "instagram_username": "darty_officiel",
            },
            {
                "name": "Boulanger",
                "website": "https://www.boulanger.com",
                "playstore_app_id": "fr.boulanger.shoppingapp",
                "appstore_app_id": "412042787",
                "instagram_username": "boulanger",
                "tiktok_username": "boulanger_officiel",
            },
            {
                "name": "Fnac",
                "website": "https://www.fnac.com",
                "playstore_app_id": "com.fnac.android",
                "appstore_app_id": "378498309",
                "instagram_username": "fnac_officiel",
                "tiktok_username": "fnac_officiel",
            },
            {
                "name": "Cdiscount",
                "website": "https://www.cdiscount.com",
                "playstore_app_id": "com.cdiscount.mobile",
                "appstore_app_id": "405498498",
                "instagram_username": "cdiscount",
                "tiktok_username": "cdiscount",
            },
            {
                "name": "LDLC",
                "website": "https://www.ldlc.com",
                "playstore_app_id": "com.ldlc.app",
                "instagram_username": "ldlc_officiel",
            },
            {
                "name": "Samsung",
                "website": "https://www.samsung.com/fr",
                "playstore_app_id": "com.sec.android.app.samsungapps",
                "instagram_username": "samsungfrance",
                "tiktok_username": "samsung",
            },
            {
                "name": "Apple",
                "website": "https://www.apple.com/fr",
                "appstore_app_id": "375380948",
                "instagram_username": "apple",
            },
            {
                "name": "Electro Dépôt",
                "website": "https://www.electrodepot.fr",
                "playstore_app_id": "com.electrodepot.app",
                "instagram_username": "electrodepot_officiel",
            },
        ],
    },
    "bricolage": {
        "name": "Bricolage & Maison",
        "competitors": [
            {
                "name": "Leroy Merlin",
                "website": "https://www.leroymerlin.fr",
                "playstore_app_id": "com.leroymerlin.franceapp",
                "appstore_app_id": "522478918",
                "instagram_username": "leroymerlin",
                "tiktok_username": "leroymerlin",
            },
            {
                "name": "Castorama",
                "website": "https://www.castorama.fr",
                "playstore_app_id": "com.castorama.selfcare",
                "appstore_app_id": "1163490666",
                "instagram_username": "castoramafrance",
            },
            {
                "name": "Bricomarché",
                "website": "https://www.bricomarche.com",
                "playstore_app_id": "com.bricomarche.app",
                "instagram_username": "bricomarche",
            },
            {
                "name": "Brico Dépôt",
                "website": "https://www.bricodepot.fr",
                "playstore_app_id": "com.bricodepot.app",
                "instagram_username": "bricodepot_france",
            },
            {
                "name": "Mr Bricolage",
                "website": "https://www.mr-bricolage.fr",
                "instagram_username": "mrbricolage_officiel",
            },
            {
                "name": "Weldom",
                "website": "https://www.weldom.fr",
                "instagram_username": "weldom_officiel",
            },
            {
                "name": "Point P",
                "website": "https://www.pointp.fr",
                "instagram_username": "pointp_officiel",
            },
        ],
    },
    "sport": {
        "name": "Sport & Outdoor",
        "competitors": [
            {
                "name": "Decathlon",
                "website": "https://www.decathlon.fr",
                "playstore_app_id": "com.decathlon.app",
                "appstore_app_id": "1079647629",
                "instagram_username": "decathlon",
                "tiktok_username": "decathlon",
            },
            {
                "name": "Intersport",
                "website": "https://www.intersport.fr",
                "playstore_app_id": "com.intersport.app",
                "instagram_username": "intersport_fr",
            },
            {
                "name": "Go Sport",
                "website": "https://www.go-sport.com",
                "playstore_app_id": "com.gosport.app",
                "instagram_username": "gosport_officiel",
            },
            {
                "name": "Sport 2000",
                "website": "https://www.sport2000.fr",
                "instagram_username": "sport2000france",
            },
            {
                "name": "Nike",
                "website": "https://www.nike.com/fr",
                "playstore_app_id": "com.nike.commerce",
                "appstore_app_id": "484790225",
                "instagram_username": "nike",
                "tiktok_username": "nike",
            },
            {
                "name": "Adidas",
                "website": "https://www.adidas.fr",
                "playstore_app_id": "com.adidas.confirmed",
                "appstore_app_id": "1001487498",
                "instagram_username": "adidas",
                "tiktok_username": "adidas",
            },
            {
                "name": "JD Sports",
                "website": "https://www.jdsports.fr",
                "playstore_app_id": "com.jdsports.app",
                "instagram_username": "jdsportsfr",
                "tiktok_username": "jdsports",
            },
            {
                "name": "Courir",
                "website": "https://www.courir.com",
                "playstore_app_id": "com.courir.app",
                "instagram_username": "couabordfr",
                "tiktok_username": "courir_sneakers",
            },
        ],
    },
    "ameublement": {
        "name": "Ameublement & Décoration",
        "competitors": [
            {
                "name": "IKEA",
                "website": "https://www.ikea.com/fr",
                "playstore_app_id": "com.ingka.ikea.app",
                "appstore_app_id": "1452164827",
                "instagram_username": "ikeafrance",
                "tiktok_username": "ikea",
            },
            {
                "name": "Maisons du Monde",
                "website": "https://www.maisonsdumonde.com",
                "playstore_app_id": "com.maisonsdumonde.app",
                "appstore_app_id": "898471498",
                "instagram_username": "maisonsdumonde",
                "tiktok_username": "maisonsdumonde",
            },
            {
                "name": "Conforama",
                "website": "https://www.conforama.fr",
                "playstore_app_id": "com.conforama.app",
                "instagram_username": "conforama_france",
            },
            {
                "name": "But",
                "website": "https://www.but.fr",
                "playstore_app_id": "fr.but.android",
                "appstore_app_id": "578478498",
                "instagram_username": "but_officiel",
            },
            {
                "name": "Alinea",
                "website": "https://www.alinea.com",
                "instagram_username": "alinea_officiel",
            },
            {
                "name": "La Redoute",
                "website": "https://www.laredoute.fr",
                "playstore_app_id": "com.laredoute.android",
                "appstore_app_id": "309498498",
                "instagram_username": "laredoute",
                "tiktok_username": "laredoute",
            },
            {
                "name": "Habitat",
                "website": "https://www.habitat.fr",
                "instagram_username": "habitat_officiel",
            },
            {
                "name": "AM.PM",
                "website": "https://www.ampm.fr",
                "instagram_username": "ampm_officiel",
            },
        ],
    },
    "restauration": {
        "name": "Restauration Rapide",
        "competitors": [
            {
                "name": "McDonald's",
                "website": "https://www.mcdonalds.fr",
                "playstore_app_id": "com.mcdonalds.mobileapp",
                "appstore_app_id": "922103212",
                "instagram_username": "mcdonaldsfrance",
                "tiktok_username": "mcdonaldsfrance",
            },
            {
                "name": "Burger King",
                "website": "https://www.burgerking.fr",
                "playstore_app_id": "fr.burgerking",
                "appstore_app_id": "1045656548",
                "instagram_username": "burgerkingfr",
                "tiktok_username": "burgerkingfr",
            },
            {
                "name": "KFC",
                "website": "https://www.kfc.fr",
                "playstore_app_id": "com.yum.kfc.fr",
                "instagram_username": "kfcfrance",
                "tiktok_username": "kfc_france",
            },
            {
                "name": "Subway",
                "website": "https://www.subway.com/fr-fr",
                "playstore_app_id": "com.subway.mobile.subwayapp09",
                "instagram_username": "subwayfrance",
            },
            {
                "name": "Domino's Pizza",
                "website": "https://www.dominos.fr",
                "playstore_app_id": "fr.dominos.android",
                "appstore_app_id": "394104498",
                "instagram_username": "dominosfrance",
                "tiktok_username": "dominosfrance",
            },
            {
                "name": "Five Guys",
                "website": "https://www.fiveguys.fr",
                "instagram_username": "fiveguysfrance",
            },
            {
                "name": "O'Tacos",
                "website": "https://www.o-tacos.com",
                "playstore_app_id": "com.otacos.app",
                "instagram_username": "otacos",
                "tiktok_username": "otacos_officiel",
            },
            {
                "name": "Starbucks",
                "website": "https://www.starbucks.fr",
                "playstore_app_id": "com.starbucks.mobilecard",
                "appstore_app_id": "331177714",
                "instagram_username": "starbucksfrance",
                "tiktok_username": "starbucks",
            },
        ],
    },
    "pharmacie": {
        "name": "Pharmacie & Parapharmacie",
        "competitors": [
            {
                "name": "Pharmacie Lafayette",
                "website": "https://www.pharmacielafayette.com",
                "playstore_app_id": "com.pharmacielafayette.app",
                "instagram_username": "pharmacie_lafayette",
            },
            {
                "name": "Pharma GDD",
                "website": "https://www.pharma-gdd.com",
                "instagram_username": "pharmagdd",
            },
            {
                "name": "Parapharmacie Leclerc",
                "website": "https://www.e.leclerc/parapharmacie",
                "instagram_username": "e.leclerc",
            },
            {
                "name": "DocMorris",
                "website": "https://www.docmorris.fr",
                "playstore_app_id": "com.docmorris.app",
                "instagram_username": "docmorris_fr",
            },
            {
                "name": "Newpharma",
                "website": "https://www.newpharma.fr",
                "instagram_username": "newpharma_fr",
            },
            {
                "name": "Cocooncenter",
                "website": "https://www.cocooncenter.com",
                "instagram_username": "cocooncenter",
            },
        ],
    },
    "optique": {
        "name": "Optique & Lunetterie",
        "competitors": [
            {
                "name": "Afflelou",
                "website": "https://www.afflelou.com",
                "playstore_app_id": "com.afflelou.app",
                "instagram_username": "afflelou",
                "tiktok_username": "afflelou",
            },
            {
                "name": "Krys",
                "website": "https://www.krys.com",
                "playstore_app_id": "com.krys.app",
                "instagram_username": "krys_officiel",
            },
            {
                "name": "Optic 2000",
                "website": "https://www.optic2000.com",
                "instagram_username": "optic2000",
            },
            {
                "name": "Générale d'Optique",
                "website": "https://www.generale-optique.com",
                "instagram_username": "generaledoptique",
            },
            {
                "name": "Atol",
                "website": "https://www.atol.fr",
                "instagram_username": "atollesopticiens",
            },
            {
                "name": "Jimmy Fairly",
                "website": "https://www.jimmyfairly.com",
                "instagram_username": "jimmyfairly",
                "tiktok_username": "jimmyfairly",
            },
        ],
    },
    "telecom": {
        "name": "Télécommunications",
        "competitors": [
            {
                "name": "Orange",
                "website": "https://www.orange.fr",
                "playstore_app_id": "com.orange.myorange.fr",
                "appstore_app_id": "417219476",
                "instagram_username": "orange",
                "tiktok_username": "orange_france",
            },
            {
                "name": "SFR",
                "website": "https://www.sfr.fr",
                "playstore_app_id": "com.sfr.android.sfr",
                "appstore_app_id": "352498498",
                "instagram_username": "sfr",
                "tiktok_username": "sfr",
            },
            {
                "name": "Bouygues Telecom",
                "website": "https://www.bouyguestelecom.fr",
                "playstore_app_id": "com.bouyguestelecom.ecm",
                "appstore_app_id": "427498498",
                "instagram_username": "bouabordelcom",
                "tiktok_username": "bouyguestelecom",
            },
            {
                "name": "Free",
                "website": "https://www.free.fr",
                "playstore_app_id": "fr.freebox.main",
                "appstore_app_id": "1475778498",
                "instagram_username": "free",
                "tiktok_username": "free_officiel",
            },
            {
                "name": "RED by SFR",
                "website": "https://www.red-by-sfr.fr",
                "instagram_username": "red_bysfr",
            },
            {
                "name": "B&You",
                "website": "https://www.bouyguestelecom.fr/forfaits/b-and-you",
                "instagram_username": "bandyou",
            },
            {
                "name": "Sosh",
                "website": "https://www.sosh.fr",
                "instagram_username": "sosh_fr",
            },
        ],
    },
    "banque": {
        "name": "Banque & Assurance",
        "competitors": [
            {
                "name": "BNP Paribas",
                "website": "https://www.bnpparibas.fr",
                "playstore_app_id": "net.bnpparibas.mescomptes",
                "appstore_app_id": "376398798",
                "instagram_username": "bnpparibas",
                "tiktok_username": "bnpparibas",
            },
            {
                "name": "Société Générale",
                "website": "https://www.societegenerale.fr",
                "playstore_app_id": "com.sg.android",
                "appstore_app_id": "373828498",
                "instagram_username": "societegenerale",
            },
            {
                "name": "Crédit Agricole",
                "website": "https://www.credit-agricole.fr",
                "playstore_app_id": "com.credit_agricole.android",
                "instagram_username": "creditagricole",
            },
            {
                "name": "LCL",
                "website": "https://www.lcl.fr",
                "playstore_app_id": "fr.lcl.android.customers",
                "instagram_username": "lcl",
            },
            {
                "name": "Boursorama",
                "website": "https://www.boursorama-banque.com",
                "playstore_app_id": "com.boursorama.android.clients",
                "appstore_app_id": "384826498",
                "instagram_username": "boursorama_banque",
                "tiktok_username": "boursorama",
            },
            {
                "name": "N26",
                "website": "https://n26.com/fr-fr",
                "playstore_app_id": "de.number26.android",
                "appstore_app_id": "956857223",
                "instagram_username": "n26",
                "tiktok_username": "n26",
            },
            {
                "name": "Revolut",
                "website": "https://www.revolut.com/fr",
                "playstore_app_id": "com.revolut.revolut",
                "appstore_app_id": "932493382",
                "instagram_username": "revolut",
                "tiktok_username": "revolut",
            },
            {
                "name": "Caisse d'Épargne",
                "website": "https://www.caisse-epargne.fr",
                "playstore_app_id": "com.caisseepargne.android.mobilebanking",
                "instagram_username": "caaborddepargne",
            },
        ],
    },
    "jardinerie": {
        "name": "Jardinerie & Animalerie",
        "competitors": [
            {
                "name": "Jardiland",
                "website": "https://www.jardiland.com",
                "playstore_app_id": "com.jardiland.fidelite",
                "instagram_username": "jardiland",
                "tiktok_username": "jardiland_officiel",
            },
            {
                "name": "Truffaut",
                "website": "https://www.truffaut.com",
                "playstore_app_id": "com.truffaut.app",
                "instagram_username": "truffaut_officiel",
            },
            {
                "name": "Gamm Vert",
                "website": "https://www.gammvert.fr",
                "instagram_username": "gammvert_officiel",
            },
            {
                "name": "Botanic",
                "website": "https://www.botanic.com",
                "instagram_username": "botanic_officiel",
            },
            {
                "name": "Animalis",
                "website": "https://www.animalis.com",
                "playstore_app_id": "com.animalis.app",
                "instagram_username": "animalis_officiel",
            },
            {
                "name": "Maxi Zoo",
                "website": "https://www.maxizoo.fr",
                "instagram_username": "maxizoo_france",
            },
        ],
    },
    "jouets": {
        "name": "Jouets & Loisirs Créatifs",
        "competitors": [
            {
                "name": "JouéClub",
                "website": "https://www.joueclub.fr",
                "playstore_app_id": "com.joueclub.app",
                "instagram_username": "joueclub",
                "tiktok_username": "joueclub",
            },
            {
                "name": "King Jouet",
                "website": "https://www.king-jouet.com",
                "playstore_app_id": "com.kingjouet.app",
                "instagram_username": "kingjouet",
            },
            {
                "name": "PicWicToys",
                "website": "https://www.picwictoys.com",
                "instagram_username": "picwictoys",
            },
            {
                "name": "La Grande Récré",
                "website": "https://www.lagranderecre.fr",
                "instagram_username": "lagranderecre",
            },
            {
                "name": "LEGO",
                "website": "https://www.lego.com/fr-fr",
                "playstore_app_id": "com.lego.bricklink.studio",
                "instagram_username": "lego",
                "tiktok_username": "lego",
            },
            {
                "name": "Cultura",
                "website": "https://www.cultura.com",
                "playstore_app_id": "com.cultura.app",
                "instagram_username": "cultura_officiel",
                "tiktok_username": "cultura_officiel",
            },
        ],
    },
    "luxe": {
        "name": "Luxe & Premium",
        "competitors": [
            {
                "name": "Louis Vuitton",
                "website": "https://www.louisvuitton.com/fra-fr",
                "playstore_app_id": "com.vuitton.android",
                "appstore_app_id": "1478199462",
                "instagram_username": "louisvuitton",
                "tiktok_username": "louisvuitton",
            },
            {
                "name": "Dior",
                "website": "https://www.dior.com/fr_fr",
                "playstore_app_id": "com.dior.app",
                "instagram_username": "dior",
                "tiktok_username": "dior",
            },
            {
                "name": "Chanel",
                "website": "https://www.chanel.com/fr",
                "instagram_username": "chanelofficial",
                "tiktok_username": "chanel",
            },
            {
                "name": "Hermès",
                "website": "https://www.hermes.com/fr/fr",
                "playstore_app_id": "com.hermes.app",
                "instagram_username": "hermes",
            },
            {
                "name": "Gucci",
                "website": "https://www.gucci.com/fr",
                "playstore_app_id": "com.gucci.app",
                "appstore_app_id": "1534634798",
                "instagram_username": "gucci",
                "tiktok_username": "gucci",
            },
            {
                "name": "Cartier",
                "website": "https://www.cartier.com/fr-fr",
                "instagram_username": "cartier",
                "tiktok_username": "cartier",
            },
            {
                "name": "Saint Laurent",
                "website": "https://www.ysl.com/fr-fr",
                "instagram_username": "ysl",
                "tiktok_username": "ysl",
            },
            {
                "name": "Balenciaga",
                "website": "https://www.balenciaga.com/fr-fr",
                "instagram_username": "balenciaga",
            },
        ],
    },
    "voyage": {
        "name": "Voyage & Tourisme",
        "competitors": [
            {
                "name": "Booking.com",
                "website": "https://www.booking.com",
                "playstore_app_id": "com.booking",
                "appstore_app_id": "367003839",
                "instagram_username": "bookingcom",
                "tiktok_username": "booking.com",
            },
            {
                "name": "Airbnb",
                "website": "https://www.airbnb.fr",
                "playstore_app_id": "com.airbnb.android",
                "appstore_app_id": "401626263",
                "instagram_username": "airbnb",
                "tiktok_username": "airbnb",
            },
            {
                "name": "SNCF Connect",
                "website": "https://www.sncf-connect.com",
                "playstore_app_id": "com.vsct.vsc.mobile.hor498.android",
                "appstore_app_id": "343889987",
                "instagram_username": "sncfconnect",
                "tiktok_username": "sncf",
            },
            {
                "name": "Lastminute",
                "website": "https://www.lastminute.com/fr",
                "playstore_app_id": "com.lastminute.mobile.android.production",
                "instagram_username": "lastminute.com",
            },
            {
                "name": "TripAdvisor",
                "website": "https://www.tripadvisor.fr",
                "playstore_app_id": "com.tripadvisor.tripadvisor",
                "appstore_app_id": "284876795",
                "instagram_username": "tripadvisor",
                "tiktok_username": "tripadvisor",
            },
            {
                "name": "Expedia",
                "website": "https://www.expedia.fr",
                "playstore_app_id": "com.expedia.bookings",
                "appstore_app_id": "427916203",
                "instagram_username": "expedia",
            },
            {
                "name": "Pierre & Vacances",
                "website": "https://www.pierreetvacances.com",
                "playstore_app_id": "com.pierreetvacances.app",
                "instagram_username": "pierreetvacances",
            },
            {
                "name": "Club Med",
                "website": "https://www.clubmed.fr",
                "playstore_app_id": "com.clubmed.android.resorts",
                "instagram_username": "clubmed",
                "tiktok_username": "clubmed",
            },
        ],
    },
    "bio": {
        "name": "Bio & Naturel",
        "competitors": [
            {
                "name": "Biocoop",
                "website": "https://www.biocoop.fr",
                "playstore_app_id": "com.biocoop.app",
                "instagram_username": "biocoop",
            },
            {
                "name": "Naturalia",
                "website": "https://www.naturalia.fr",
                "playstore_app_id": "com.naturalia.app",
                "instagram_username": "naturalia_magasins_bio",
            },
            {
                "name": "La Vie Claire",
                "website": "https://www.lavieclaire.com",
                "instagram_username": "lavieclaire_bio",
            },
            {
                "name": "Bio c' Bon",
                "website": "https://www.bio-c-bon.eu",
                "instagram_username": "biocbon",
            },
            {
                "name": "Marcel & Fils",
                "website": "https://www.marcel-et-fils.com",
                "instagram_username": "marceletfils",
            },
            {
                "name": "L'Eau Vive",
                "website": "https://www.eau-vive.com",
                "instagram_username": "leauvive_bio",
            },
        ],
    },
    "automobile": {
        "name": "Automobile",
        "competitors": [
            {
                "name": "Renault",
                "website": "https://www.renault.fr",
                "playstore_app_id": "com.renault.myrenault",
                "appstore_app_id": "1076667498",
                "instagram_username": "renault_france",
                "tiktok_username": "renault",
            },
            {
                "name": "Peugeot",
                "website": "https://www.peugeot.fr",
                "playstore_app_id": "com.psa.mypeugeot",
                "instagram_username": "peugeot",
                "tiktok_username": "peugeot",
            },
            {
                "name": "Citroën",
                "website": "https://www.citroen.fr",
                "playstore_app_id": "com.psa.mycitroen",
                "instagram_username": "citroen",
                "tiktok_username": "citroen",
            },
            {
                "name": "Volkswagen",
                "website": "https://www.volkswagen.fr",
                "playstore_app_id": "de.volkswagen.car-net.eu.e-remote",
                "instagram_username": "volkswagen_fr",
            },
            {
                "name": "Toyota",
                "website": "https://www.toyota.fr",
                "playstore_app_id": "com.toyota.oneapp.eu",
                "instagram_username": "toyotafrance",
            },
            {
                "name": "BMW",
                "website": "https://www.bmw.fr",
                "playstore_app_id": "de.bmw.connected.mobile20.row",
                "instagram_username": "bmwfrance",
                "tiktok_username": "bmw",
            },
            {
                "name": "Tesla",
                "website": "https://www.tesla.com/fr_fr",
                "playstore_app_id": "com.teslamotors.tesla",
                "appstore_app_id": "582007913",
                "instagram_username": "teslamotors",
                "tiktok_username": "tesla",
            },
            {
                "name": "Mercedes-Benz",
                "website": "https://www.mercedes-benz.fr",
                "playstore_app_id": "com.daimler.ris.mercedesme.ece",
                "instagram_username": "mercedesbenzfr",
            },
        ],
    },
}


def get_sector_label(sector_code: str) -> str:
    """Retourne le nom complet d'un secteur."""
    return SECTORS.get(sector_code, {}).get("name", sector_code)


def get_competitors_for_sector(sector_code: str) -> list:
    """Retourne la liste des concurrents pré-configurés pour un secteur."""
    return SECTORS.get(sector_code, {}).get("competitors", [])


def list_sectors() -> list:
    """Retourne la liste des secteurs disponibles."""
    return [
        {"code": code, "name": data["name"], "competitors_count": len(data["competitors"])}
        for code, data in SECTORS.items()
    ]
