"""
Secteurs et concurrents pré-configurés.
Base de connaissance métier pour le retail français.
"""

SECTORS = {
    "supermarche": {
        "name": "Grande Distribution",
        "competitors": [
            {
                "name": "Carrefour",
                "website": "https://www.carrefour.fr",
                "playstore_app_id": "com.carrefour.fid.android",
                "appstore_app_id": "378305156",
                "instagram_username": "carrefourfrance",
                "tiktok_username": "carrefourfrance",
                "youtube_channel_id": "UCNQ_I8AhYrV9y1uTWVNTTtA",
                "snapchat_entity_name": "Carrefour",
                "snapchat_username": "carrefourfrance",
            },
            {
                "name": "Leclerc",
                "website": "https://www.e.leclerc",
                "playstore_app_id": "com.infomil.bill",
                "appstore_app_id": "756693888",
                "instagram_username": "leclerc",
                "tiktok_username": "leclerc",
                "youtube_channel_id": "UCrnLMg8vyroKjPQS-IX7Opg",
                "snapchat_entity_name": "E.Leclerc",
                "snapchat_username": "e.leclerc",
            },
            {
                "name": "Auchan",
                "website": "https://www.auchan.fr",
                "playstore_app_id": "com.auchan.android",
                "appstore_app_id": "393068659",
                "instagram_username": "auchan_france",
                "tiktok_username": "auchan_fr",
                "youtube_channel_id": "UCmciQZyg87a2bz9OYP8Lpdg",
                "snapchat_entity_name": "Auchan",
                "snapchat_username": "auchan",
            },
            {
                "name": "Intermarché",
                "website": "https://www.intermarche.com",
                "playstore_app_id": "com.intermarche.mobile.courses",
                "appstore_app_id": "1447048498",
                "instagram_username": "intermarche",
                "tiktok_username": "intermarche_france",
                "youtube_channel_id": "UC2pAIqBgaTxNbNRLPfsZdnw",
                "snapchat_entity_name": "Intermarché",
                "snapchat_username": "intermarche",
            },
            {
                "name": "Lidl",
                "website": "https://www.lidl.fr",
                "playstore_app_id": "com.lidl.eci.lidlplus",
                "appstore_app_id": "1238611143",
                "instagram_username": "lidlfrance",
                "tiktok_username": "lidlfrance",
                "youtube_channel_id": "UCRMu2Bs7litn7jfnrh-STXA",
                "snapchat_entity_name": "Lidl",
                "snapchat_username": "lidlfrance",
            },
            {
                "name": "Monoprix",
                "website": "https://www.monoprix.fr",
                "playstore_app_id": "fr.monoprix.monoprix",
                "appstore_app_id": "966459890",
                "instagram_username": "monoprix",
                "tiktok_username": "monoprix",
                "youtube_channel_id": "UCUFmvsGtcpYpEBoW04rm5Gw",
            },
            {
                "name": "Casino",
                "website": "https://www.casino.fr",
                "facebook_page_id": "CasinoFranceOfficiel",
                "playstore_app_id": "fr.casino.fidelite",
                "appstore_app_id": "1273195340",
                "instagram_username": "casinosupermarches",
                "tiktok_username": "casino_france",
                "youtube_channel_id": "UC8rEGNIeih9VLNpaUjkypXA",
            },
            {
                "name": "Système U",
                "website": "https://www.magasins-u.com",
                "playstore_app_id": "com.systeme_u.courseu",
                "appstore_app_id": "557548411",
                "instagram_username": "ulescommercants",
                "tiktok_username": "ulescommercants",
                "youtube_channel_id": "UC64Dt3bVFWVxKnd4pafs1aA",
            },
            {
                "name": "Franprix",
                "website": "https://www.franprix.fr",
                "playstore_app_id": "fr.franprix.app",
                "appstore_app_id": "6463642642",
                "instagram_username": "franprix",
                "tiktok_username": "franprix_fr",
                "youtube_channel_id": "UCoOvNRuTeMyIQUSvoc8T1-g",
            },
            {
                "name": "Picard",
                "website": "https://www.picard.fr",
                "playstore_app_id": "com.picard.app",
                "appstore_app_id": "1507741802",
                "instagram_username": "picardsurgeles",
                "tiktok_username": "picardsurgeles",
                "youtube_channel_id": "UCWcZLeLK7y9mUG9DU5KCSDA",
            },
            {
                "name": "Grand Frais",
                "website": "https://www.grandfrais.com",
                "instagram_username": "grandfrais_officiel",
                "tiktok_username": "grandfraisfr",
                "youtube_channel_id": "UCy_xVTDSgxFrqr4Yx35is3g",
            },
            {
                "name": "Aldi",
                "website": "https://www.aldi.fr",
                "playstore_app_id": "com.aldi.mobile",
                "appstore_app_id": "579350544",
                "instagram_username": "aldi.france",
                "tiktok_username": "aldi.france",
                "youtube_channel_id": "UCH6ncdjBHRkTiuaSq2pkvSQ",
            },
        ],
    },
    "mode": {
        "name": "Mode & Habillement",
        "competitors": [
            {
                "name": "Zara",
                "website": "https://www.zara.com/fr",
                "playstore_app_id": "com.inditex.zara",
                "appstore_app_id": "547347221",
                "instagram_username": "zara",
                "tiktok_username": "zara",
            },
            {
                "name": "H&M",
                "website": "https://www.hm.com/fr",
                "playstore_app_id": "com.hm.goe",
                "appstore_app_id": "834465911",
                "instagram_username": "hm",
                "tiktok_username": "hm",
                "youtube_channel_id": "UCoc8tpGCY1wrp8pV7mI0scA",
            },
            {
                "name": "Kiabi",
                "website": "https://www.kiabi.com",
                "playstore_app_id": "com.kiabi.app",
                "appstore_app_id": "495571498",
                "instagram_username": "kiabi_official",
                "tiktok_username": "kiabi_official",
            },
            {
                "name": "Primark",
                "website": "https://www.primark.com/fr",
                "playstore_app_id": "com.primark.app.prod",
                "appstore_app_id": "6745568862",
                "instagram_username": "primark",
                "tiktok_username": "primark",
            },
            {
                "name": "Uniqlo",
                "website": "https://www.uniqlo.com/fr",
                "playstore_app_id": "com.uniqlo.europe.catalogue",
                "appstore_app_id": "6503727839",
                "instagram_username": "uniqlo",
                "tiktok_username": "uniqlo",
            },
            {
                "name": "C&A",
                "website": "https://www.c-and-a.com/fr",
                "playstore_app_id": "com.canda.app",
                "appstore_app_id": "1462636376",
                "instagram_username": "ca",
                "tiktok_username": "ca",
            },
            {
                "name": "Jules",
                "website": "https://www.jules.com",
                "playstore_app_id": "com.jules.app",
                "appstore_app_id": "972123111",
                "instagram_username": "jules",
                "tiktok_username": "jules",
            },
            {
                "name": "Celio",
                "website": "https://www.celio.com",
                "playstore_app_id": "com.celio.mobileshopper",
                "instagram_username": "celio_officiel",
                "tiktok_username": "celio_benormal",
            },
            {
                "name": "Mango",
                "website": "https://www.mango.com/fr",
                "playstore_app_id": "com.mango.mango",
                "appstore_app_id": "372216941",
                "instagram_username": "mango",
                "tiktok_username": "mango",
            },
            {
                "name": "Bonobo",
                "website": "https://www.bonoboplanet.com",
                "instagram_username": "bonoboplanet",
                "tiktok_username": "bonobojeans",
            },
            {
                "name": "Pimkie",
                "website": "https://www.pimkie.fr",
                "playstore_app_id": "com.pimkie.app",
                "appstore_app_id": "897026650",
                "instagram_username": "pimkie",
                "tiktok_username": "pimkie.official",
            },
            {
                "name": "Camaïeu",
                "website": "https://www.camaieu.fr",
                "instagram_username": "camaieu",
                "tiktok_username": "camaieufr",
            },
        ],
    },
    "beaute": {
        "name": "Beauté & Cosmétiques",
        "competitors": [
            {
                "name": "Sephora",
                "website": "https://www.sephora.fr",
                "playstore_app_id": "com.sephora.android",
                "appstore_app_id": "393328150",
                "instagram_username": "sephorafrance",
                "tiktok_username": "sephora",
            },
            {
                "name": "Nocibé",
                "website": "https://www.nocibe.fr",
                "playstore_app_id": "com.douglas.nocibe",
                "appstore_app_id": "1123649654",
                "instagram_username": "nocibe_france",
                "tiktok_username": "nocibe_france",
            },
            {
                "name": "Yves Rocher",
                "website": "https://www.yves-rocher.fr",
                "playstore_app_id": "com.yvesrocher.yvesrocher",
                "appstore_app_id": "485296924",
                "instagram_username": "yvesrocherusa",
                "tiktok_username": "yvesrocher",
                "youtube_channel_id": "UCYCEvnHr3OH-WAUI8xWjU3w",
            },
            {
                "name": "Marionnaud",
                "website": "https://www.marionnaud.fr",
                "playstore_app_id": "com.marionnaud.marionnaudfrance",
                "appstore_app_id": "1127368763",
                "instagram_username": "marionnaud_france",
                "tiktok_username": "marionnaudfrance",
            },
            {
                "name": "L'Occitane",
                "website": "https://www.loccitane.com/fr",
                "playstore_app_id": "com.loccitane.android",
                "appstore_app_id": "603378498",
                "instagram_username": "loccitane",
                "tiktok_username": "loccitane",
                "youtube_channel_id": "UCNavI7VPbI3Nx5pCTHFv_1g",
            },
            {
                "name": "Rituals",
                "website": "https://www.rituals.com/fr-fr",
                "playstore_app_id": "com.rituals.app.prod",
                "appstore_app_id": "1424241203",
                "instagram_username": "rituals",
                "tiktok_username": "rituals",
            },
            {
                "name": "Kiko Milano",
                "website": "https://www.kikocosmetics.com/fr-fr",
                "playstore_app_id": "com.kikocosmetics.android.app",
                "appstore_app_id": "939604624",
                "instagram_username": "kikomilano",
                "tiktok_username": "kikomilano",
            },
            {
                "name": "Lush",
                "website": "https://www.lush.com/fr",
                "playstore_app_id": "com.lush.app",
                "appstore_app_id": "946403534",
                "instagram_username": "lushfrance",
                "tiktok_username": "lush",
            },
            {
                "name": "MAC Cosmetics",
                "website": "https://www.maccosmetics.fr",
                "playstore_app_id": "com.elc.macx",
                "appstore_app_id": "6496204335",
                "instagram_username": "maccosmetics",
                "tiktok_username": "maccosmetics",
            },
            {
                "name": "NYX Professional Makeup",
                "website": "https://www.nyxcosmetics.fr",
                "instagram_username": "nyxcosmetics_france",
                "tiktok_username": "nyxcosmetics",
            },
        ],
    },
    "electromenager": {
        "name": "Électroménager & High-Tech",
        "competitors": [
            {
                "name": "Darty",
                "website": "https://www.darty.com",
                "playstore_app_id": "com.darty.app",
                "appstore_app_id": "352210890",
                "instagram_username": "darty_officiel",
                "tiktok_username": "darty_officiel",
                "youtube_channel_id": "UC_zgf8leGKSXNLLyCYP9PeQ",
            },
            {
                "name": "Boulanger",
                "website": "https://www.boulanger.com",
                "playstore_app_id": "fr.boulanger.shoppingapp",
                "appstore_app_id": "412042787",
                "instagram_username": "boulanger",
                "tiktok_username": "boulanger_officiel",
            },
            {
                "name": "Fnac",
                "website": "https://www.fnac.com",
                "playstore_app_id": "com.fnac.android",
                "appstore_app_id": "378498309",
                "instagram_username": "fnac_officiel",
                "tiktok_username": "fnac_officiel",
            },
            {
                "name": "Cdiscount",
                "website": "https://www.cdiscount.com",
                "playstore_app_id": "com.cdiscount.mobile",
                "appstore_app_id": "398364165",
                "instagram_username": "cdiscount",
                "tiktok_username": "cdiscount",
            },
            {
                "name": "LDLC",
                "website": "https://www.ldlc.com",
                "playstore_app_id": "com.groupeldlc.ldlcapp",
                "appstore_app_id": "6746115799",
                "instagram_username": "ldlc_officiel",
                "tiktok_username": "ldlc.com",
            },
            {
                "name": "Samsung",
                "website": "https://www.samsung.com/fr",
                "playstore_app_id": "com.sec.android.app.samsungapps",
                "instagram_username": "samsungfrance",
                "tiktok_username": "samsung",
                "youtube_channel_id": "UCBTDxCoWmk9O6M6g0y_vjZg",
            },
            {
                "name": "Apple",
                "website": "https://www.apple.com/fr",
                "appstore_app_id": "375380948",
                "instagram_username": "apple",
                "tiktok_username": "apple",
                "youtube_channel_id": "UCE_M8A5yxnLfW0KghEeajjw",
            },
            {
                "name": "Electro Dépôt",
                "website": "https://www.electrodepot.fr",
                "playstore_app_id": "com.pictime.electrodepot",
                "appstore_app_id": "503563848",
                "instagram_username": "electrodepot_officiel",
                "tiktok_username": "electrodepotfr",
            },
        ],
    },
    "bricolage": {
        "name": "Bricolage & Maison",
        "competitors": [
            {
                "name": "Leroy Merlin",
                "website": "https://www.leroymerlin.fr",
                "playstore_app_id": "com.leroymerlin.franceapp",
                "appstore_app_id": "522478918",
                "instagram_username": "leroymerlin",
                "tiktok_username": "leroymerlin",
                "youtube_channel_id": "UCSUsedzrYjYrzzT4WTDTTIw",
            },
            {
                "name": "Castorama",
                "website": "https://www.castorama.fr",
                "playstore_app_id": "com.castorama.selfcare",
                "appstore_app_id": "1163490666",
                "instagram_username": "castoramafrance",
                "tiktok_username": "castorama",
                "youtube_channel_id": "UCKFpWQOvBT2GNNG05xCs9GA",
            },
            {
                "name": "Bricomarché",
                "website": "https://www.bricomarche.com",
                "playstore_app_id": "fr.stime.inc.bricomarche",
                "appstore_app_id": "1462744119",
                "instagram_username": "bricomarche",
            },
            {
                "name": "Brico Dépôt",
                "website": "https://www.bricodepot.fr",
                "playstore_app_id": "com.bricodepot.fidelitepro",
                "appstore_app_id": "6466879378",
                "instagram_username": "bricodepot_france",
                "tiktok_username": "bricodepot",
                "youtube_channel_id": "UC7GZ6NqxeqHz0MnsllLEhbw",
            },
            {
                "name": "Mr Bricolage",
                "website": "https://www.mr-bricolage.fr",
                "instagram_username": "mrbricolage_officiel",
            },
            {
                "name": "Weldom",
                "website": "https://www.weldom.fr",
                "playstore_app_id": "com.weldom",
                "appstore_app_id": "643238535",
                "instagram_username": "weldom_officiel",
                "tiktok_username": "weldomfrance",
                "youtube_channel_id": "UC5ZflZDaJi4pKCjGaa-5MLQ",
            },
            {
                "name": "Point P",
                "website": "https://www.pointp.fr",
                "playstore_app_id": "com.pointp.android",
                "appstore_app_id": "634317935",
                "instagram_username": "pointp_officiel",
                "tiktok_username": "pointp_fr",
            },
        ],
    },
    "sport": {
        "name": "Sport & Outdoor",
        "competitors": [
            {
                "name": "Decathlon",
                "website": "https://www.decathlon.fr",
                "playstore_app_id": "com.decathlon.app",
                "appstore_app_id": "1079647629",
                "instagram_username": "decathlon",
                "tiktok_username": "decathlon",
                "youtube_channel_id": "UCUq8JEJ0_NV_izL0xth4IiA",
            },
            {
                "name": "Intersport",
                "website": "https://www.intersport.fr",
                "playstore_app_id": "com.intersport.app",
                "appstore_app_id": "6474043527",
                "instagram_username": "intersport_fr",
                "tiktok_username": "intersportfr",
                "youtube_channel_id": "UCDS_mA4bqfkCp1OqoMh_lGA",
            },
            {
                "name": "Go Sport",
                "website": "https://www.go-sport.com",
                "playstore_app_id": "com.gosport.app",
                "instagram_username": "gosport_officiel",
                "tiktok_username": "gosportfrance",
            },
            {
                "name": "Sport 2000",
                "website": "https://www.sport2000.fr",
                "playstore_app_id": "com.sportheroes.livretsport",
                "appstore_app_id": "1584144369",
                "instagram_username": "sport2000france",
                "tiktok_username": "sport2000france",
                "youtube_channel_id": "UCEYk7XT0qB5A8Ih4NsQVcSA",
            },
            {
                "name": "Nike",
                "website": "https://www.nike.com/fr",
                "playstore_app_id": "com.nike.commerce",
                "appstore_app_id": "484790225",
                "instagram_username": "nike",
                "tiktok_username": "nike",
                "youtube_channel_id": "UCUFgkRb0ZHc4Rpq15VRCICA",
            },
            {
                "name": "Adidas",
                "website": "https://www.adidas.fr",
                "playstore_app_id": "com.adidas.confirmed",
                "appstore_app_id": "1001487498",
                "instagram_username": "adidas",
                "tiktok_username": "adidas",
                "youtube_channel_id": "UCuLUOxd7ezJ8c6NSLBNRRfg",
            },
            {
                "name": "JD Sports",
                "website": "https://www.jdsports.fr",
                "playstore_app_id": "com.jdsports.app",
                "appstore_app_id": "690602681",
                "instagram_username": "jdsportsfr",
                "tiktok_username": "jdsports",
                "youtube_channel_id": "UCA3oGAAHcYVK3I55G7xY67A",
            },
            {
                "name": "Courir",
                "website": "https://www.courir.com",
                "playstore_app_id": "com.courir.app",
                "instagram_username": "courir",
                "tiktok_username": "courir_sneakers",
                "youtube_channel_id": "UCLYo5hQ4G5iR-CzU71oOr6Q",
            },
        ],
    },
    "ameublement": {
        "name": "Ameublement & Décoration",
        "competitors": [
            {
                "name": "IKEA",
                "website": "https://www.ikea.com/fr",
                "playstore_app_id": "com.ingka.ikea.app",
                "appstore_app_id": "1452164827",
                "instagram_username": "ikeafrance",
                "tiktok_username": "ikea",
                "youtube_channel_id": "UCXzI0Bp-qeP80W6C7dgsjOg",
            },
            {
                "name": "Maisons du Monde",
                "website": "https://www.maisonsdumonde.com",
                "playstore_app_id": "com.maisonsdumonde.app",
                "appstore_app_id": "898471498",
                "instagram_username": "maisonsdumonde",
                "tiktok_username": "maisonsdumonde",
                "youtube_channel_id": "UCvDz46dvR6tEJoHtmYPcmBA",
            },
            {
                "name": "Conforama",
                "website": "https://www.conforama.fr",
                "playstore_app_id": "com.conforama.app",
                "appstore_app_id": "1037820199",
                "instagram_username": "conforama_france",
                "tiktok_username": "conforama",
                "youtube_channel_id": "UC_21RieYsYvHsdm6O6oufzA",
            },
            {
                "name": "But",
                "website": "https://www.but.fr",
                "playstore_app_id": "fr.but.android",
                "appstore_app_id": "578478498",
                "instagram_username": "but_officiel",
            },
            {
                "name": "Alinea",
                "website": "https://www.alinea.com",
                "instagram_username": "alinea_officiel",
            },
            {
                "name": "La Redoute",
                "website": "https://www.laredoute.fr",
                "playstore_app_id": "com.laredoute.android",
                "appstore_app_id": "393136788",
                "instagram_username": "laredoute",
                "tiktok_username": "laredoute",
                "youtube_channel_id": "UC2pLRq0rtiQQku0YxntO2xw",
            },
            {
                "name": "Habitat",
                "website": "https://www.habitat.fr",
                "instagram_username": "habitat_officiel",
            },
            {
                "name": "AM.PM",
                "website": "https://www.ampm.fr",
                "instagram_username": "ampm_officiel",
            },
        ],
    },
    "restauration": {
        "name": "Restauration Rapide",
        "competitors": [
            {
                "name": "McDonald's",
                "website": "https://www.mcdonalds.fr",
                "playstore_app_id": "com.mcdonalds.mobileapp",
                "appstore_app_id": "922103212",
                "instagram_username": "mcdonaldsfrance",
                "tiktok_username": "mcdonaldsfrance",
                "youtube_channel_id": "UC2_6yNdzqnTG8QxaeOdD_0g",
            },
            {
                "name": "Burger King",
                "website": "https://www.burgerking.fr",
                "playstore_app_id": "fr.burgerking",
                "appstore_app_id": "1045656548",
                "instagram_username": "burgerkingfr",
                "tiktok_username": "burgerkingfr",
                "youtube_channel_id": "UC7xkj-B5JURNClrvM0EsUNA",
            },
            {
                "name": "KFC",
                "website": "https://www.kfc.fr",
                "playstore_app_id": "com.yum.kfc.fr",
                "appstore_app_id": "1622002883",
                "instagram_username": "kfcfrance",
                "tiktok_username": "kfc_france",
                "youtube_channel_id": "UCnDx5LooMLSxV5CHzDYus7A",
            },
            {
                "name": "Subway",
                "website": "https://www.subway.com/fr-fr",
                "playstore_app_id": "com.subway.mobile.subwayapp09",
                "appstore_app_id": "901941015",
                "instagram_username": "subwayfrance",
                "tiktok_username": "subwayfrance",
                "youtube_channel_id": "UC4dRakuUqCjRVhBXdMj82eQ",
            },
            {
                "name": "Domino's Pizza",
                "website": "https://www.dominos.fr",
                "playstore_app_id": "fr.dominos.android",
                "appstore_app_id": "596817115",
                "instagram_username": "dominosfrance",
                "tiktok_username": "dominosfrance",
                "youtube_channel_id": "UCQGt3HttTUgez4RCJnqf5lg",
            },
            {
                "name": "Five Guys",
                "website": "https://www.fiveguys.fr",
                "playstore_app_id": "com.fiveguys.fiveguysuk",
                "appstore_app_id": "683336616",
                "instagram_username": "fiveguysfrance",
                "tiktok_username": "fiveguysfrance",
            },
            {
                "name": "O'Tacos",
                "website": "https://www.o-tacos.com",
                "playstore_app_id": "com.otacos.app",
                "appstore_app_id": "1510837681",
                "instagram_username": "otacos",
                "tiktok_username": "otacos_officiel",
                "youtube_channel_id": "UC81poO9501wV6jr83JgxYaA",
            },
            {
                "name": "Starbucks",
                "website": "https://www.starbucks.fr",
                "playstore_app_id": "com.starbucks.mobilecard",
                "appstore_app_id": "331177714",
                "instagram_username": "starbucksfrance",
                "tiktok_username": "starbucks",
                "youtube_channel_id": "UCaNgxgi8tasCh-MZKhegeGw",
            },
        ],
    },
    "pharmacie": {
        "name": "Pharmacie & Parapharmacie",
        "competitors": [
            {
                "name": "Pharmacie Lafayette",
                "website": "https://www.pharmacielafayette.com",
                "playstore_app_id": "com.itekcommunication.pharmacielafayette",
                "appstore_app_id": "956521486",
                "instagram_username": "pharmacie_lafayette",
                "tiktok_username": "pharmacie_lafayette",
            },
            {
                "name": "Pharma GDD",
                "website": "https://www.pharma-gdd.com",
                "instagram_username": "pharmagdd",
            },
            {
                "name": "Parapharmacie Leclerc",
                "website": "https://www.e.leclerc/parapharmacie",
                "instagram_username": "e.leclerc",
            },
            {
                "name": "DocMorris",
                "website": "https://www.docmorris.fr",
                "playstore_app_id": "com.docmorris.app",
                "appstore_app_id": "1473123438",
                "instagram_username": "docmorris_fr",
            },
            {
                "name": "Newpharma",
                "website": "https://www.newpharma.fr",
                "instagram_username": "newpharma_fr",
            },
            {
                "name": "Cocooncenter",
                "website": "https://www.cocooncenter.com",
                "instagram_username": "cocooncenter",
            },
        ],
    },
    "optique": {
        "name": "Optique & Lunetterie",
        "competitors": [
            {
                "name": "Afflelou",
                "website": "https://www.afflelou.com",
                "playstore_app_id": "com.afflelou.app",
                "instagram_username": "afflelou",
                "tiktok_username": "afflelou",
            },
            {
                "name": "Krys",
                "website": "https://www.krys.com",
                "playstore_app_id": "com.krys.app",
                "instagram_username": "krys_officiel",
                "tiktok_username": "krys.officiel",
            },
            {
                "name": "Optic 2000",
                "website": "https://www.optic2000.com",
                "appstore_app_id": "1565514061",
                "instagram_username": "optic2000",
            },
            {
                "name": "Générale d'Optique",
                "website": "https://www.generale-optique.com",
                "instagram_username": "generaledoptique",
                "tiktok_username": "generaleoptique",
            },
            {
                "name": "Atol",
                "website": "https://www.atol.fr",
                "instagram_username": "atollesopticiens",
                "tiktok_username": "atollesopticiens",
            },
            {
                "name": "Jimmy Fairly",
                "website": "https://www.jimmyfairly.com",
                "instagram_username": "jimmyfairly",
                "tiktok_username": "jimmyfairly",
            },
        ],
    },
    "telecom": {
        "name": "Télécommunications",
        "competitors": [
            {
                "name": "Orange",
                "website": "https://www.orange.fr",
                "playstore_app_id": "com.orange.myorange.fr",
                "appstore_app_id": "367722531",
                "instagram_username": "orange",
                "tiktok_username": "orange_france",
            },
            {
                "name": "SFR",
                "website": "https://www.sfr.fr",
                "playstore_app_id": "com.sfr.android.sfr",
                "appstore_app_id": "326161564",
                "instagram_username": "sfr",
                "tiktok_username": "sfr",
            },
            {
                "name": "Bouygues Telecom",
                "website": "https://www.bouyguestelecom.fr",
                "playstore_app_id": "com.bouyguestelecom.ecm",
                "appstore_app_id": "422590767",
                "instagram_username": "bouyguestelecom",
                "tiktok_username": "bouyguestelecom",
                "youtube_channel_id": "UCfcVlVplwcHZNrQpeXmeHTQ",
            },
            {
                "name": "Free",
                "website": "https://www.free.fr",
                "playstore_app_id": "fr.freebox.main",
                "appstore_app_id": "1643534870",
                "instagram_username": "free",
                "tiktok_username": "free_officiel",
            },
            {
                "name": "RED by SFR",
                "website": "https://www.red-by-sfr.fr",
                "instagram_username": "red_bysfr",
            },
            {
                "name": "B&You",
                "website": "https://www.bouyguestelecom.fr/forfaits/b-and-you",
                "instagram_username": "bandyou",
            },
            {
                "name": "Sosh",
                "website": "https://www.sosh.fr",
                "instagram_username": "sosh_fr",
            },
        ],
    },
    "banque": {
        "name": "Banque & Assurance",
        "competitors": [
            {
                "name": "BNP Paribas",
                "website": "https://www.bnpparibas.fr",
                "playstore_app_id": "net.bnpparibas.mescomptes",
                "appstore_app_id": "377884617",
                "instagram_username": "bnpparibas",
                "tiktok_username": "bnpparibas",
            },
            {
                "name": "Société Générale",
                "website": "https://www.societegenerale.fr",
                "playstore_app_id": "com.sg.android",
                "appstore_app_id": "376991016",
                "instagram_username": "societegenerale",
                "tiktok_username": "societe_generale",
            },
            {
                "name": "Crédit Agricole",
                "website": "https://www.credit-agricole.fr",
                "playstore_app_id": "com.credit_agricole.android",
                "appstore_app_id": "376202925",
                "instagram_username": "creditagricole",
                "tiktok_username": "creditagricole",
            },
            {
                "name": "LCL",
                "website": "https://www.lcl.fr",
                "playstore_app_id": "fr.lcl.android.customers",
                "appstore_app_id": "420923807",
                "instagram_username": "lcl",
                "tiktok_username": "lcl",
            },
            {
                "name": "Boursorama",
                "website": "https://www.boursorama-banque.com",
                "playstore_app_id": "com.boursorama.android.clients",
                "appstore_app_id": "425368900",
                "instagram_username": "boursorama_banque",
                "tiktok_username": "boursorama",
            },
            {
                "name": "N26",
                "website": "https://n26.com/fr-fr",
                "playstore_app_id": "de.number26.android",
                "appstore_app_id": "956857223",
                "instagram_username": "n26",
                "tiktok_username": "n26",
            },
            {
                "name": "Revolut",
                "website": "https://www.revolut.com/fr",
                "playstore_app_id": "com.revolut.revolut",
                "appstore_app_id": "932493382",
                "instagram_username": "revolut",
                "tiktok_username": "revolut",
            },
            {
                "name": "Caisse d'Épargne",
                "website": "https://www.caisse-epargne.fr",
                "playstore_app_id": "com.caisseepargne.android.mobilebanking",
                "appstore_app_id": "402753249",
                "instagram_username": "caisse_epargne",
                "tiktok_username": "caisse_epargne",
            },
        ],
    },
    "jardinerie": {
        "name": "Jardinerie & Animalerie",
        "competitors": [
            {
                "name": "Jardiland",
                "website": "https://www.jardiland.com",
                "playstore_app_id": "com.jardiland.fidelite",
                "appstore_app_id": "382583742",
                "instagram_username": "jardiland",
                "tiktok_username": "jardiland_officiel",
                "youtube_channel_id": "UCFZXu_nYO74ZZKTiOezmdCw",
            },
            {
                "name": "Truffaut",
                "website": "https://www.truffaut.com",
                "playstore_app_id": "com.truffaut.app",
                "appstore_app_id": "957349049",
                "instagram_username": "truffaut_officiel",
                "tiktok_username": "jardineriestruffaut",
            },
            {
                "name": "Gamm Vert",
                "website": "https://www.gammvert.fr",
                "instagram_username": "gammvert_officiel",
            },
            {
                "name": "Botanic",
                "website": "https://www.botanic.com",
                "instagram_username": "botanic_officiel",
                "tiktok_username": "botanic_france",
                "youtube_channel_id": "UC3mMTjiDsiP1q_cGAUuZWBA",
            },
            {
                "name": "Animalis",
                "website": "https://www.animalis.com",
                "playstore_app_id": "com.animalis.app",
                "appstore_app_id": "6751287441",
                "instagram_username": "animalis_officiel",
                "tiktok_username": "animalis_fr",
            },
            {
                "name": "Maxi Zoo",
                "website": "https://www.maxizoo.fr",
                "playstore_app_id": "com.fressnapf.mobileapp",
                "appstore_app_id": "1555501888",
                "instagram_username": "maxizoo_france",
                "tiktok_username": "maxizoo.france",
                "youtube_channel_id": "UC6BqpnOrrPTue5Pk20qLgMQ",
            },
        ],
    },
    "jouets": {
        "name": "Jouets & Loisirs Créatifs",
        "competitors": [
            {
                "name": "JouéClub",
                "website": "https://www.joueclub.fr",
                "playstore_app_id": "com.joueclub.app",
                "appstore_app_id": "6466821065",
                "instagram_username": "joueclub",
                "tiktok_username": "joueclub",
                "youtube_channel_id": "UCgzACnbHsOfi7kGfk_dFSxg",
            },
            {
                "name": "King Jouet",
                "website": "https://www.king-jouet.com",
                "playstore_app_id": "com.kingjouet.app",
                "appstore_app_id": "1160133152",
                "instagram_username": "kingjouet",
                "tiktok_username": "kingjouet_fr",
            },
            {
                "name": "PicWicToys",
                "website": "https://www.picwictoys.com",
                "instagram_username": "picwictoys",
            },
            {
                "name": "La Grande Récré",
                "website": "https://www.lagranderecre.fr",
                "playstore_app_id": "fr.lagranderecre.magrandefamille",
                "instagram_username": "lagranderecre",
                "youtube_channel_id": "UCy2IPyHPapI6tEX2VB-ngSg",
            },
            {
                "name": "LEGO",
                "website": "https://www.lego.com/fr-fr",
                "playstore_app_id": "com.lego.bricklink.studio",
                "instagram_username": "lego",
                "tiktok_username": "lego",
            },
            {
                "name": "Cultura",
                "website": "https://www.cultura.com",
                "playstore_app_id": "com.cultura.app",
                "instagram_username": "cultura_officiel",
                "tiktok_username": "culturafr",
            },
        ],
    },
    "luxe": {
        "name": "Luxe & Premium",
        "competitors": [
            {
                "name": "Louis Vuitton",
                "website": "https://www.louisvuitton.com/fra-fr",
                "playstore_app_id": "com.vuitton.android",
                "appstore_app_id": "1478199462",
                "instagram_username": "louisvuitton",
                "tiktok_username": "louisvuitton",
                "youtube_channel_id": "UC5q0PIKGr2lGOsiT14AlEYg",
            },
            {
                "name": "Dior",
                "website": "https://www.dior.com/fr_fr",
                "playstore_app_id": "com.dior.app",
                "instagram_username": "dior",
                "tiktok_username": "dior",
                "youtube_channel_id": "UC6xD-jKli-_qIYXDTsNv4dw",
            },
            {
                "name": "Chanel",
                "website": "https://www.chanel.com/fr",
                "appstore_app_id": "409934435",
                "instagram_username": "chanelofficial",
                "tiktok_username": "chanel",
                "youtube_channel_id": "UCclHSnngVTZK7LEOQAzcg1w",
            },
            {
                "name": "Hermès",
                "website": "https://www.hermes.com/fr/fr",
                "playstore_app_id": "com.hermes.app",
                "instagram_username": "hermes",
                "youtube_channel_id": "UCmFOnqrNg-YHLXfdB3GexBg",
            },
            {
                "name": "Gucci",
                "website": "https://www.gucci.com/fr",
                "playstore_app_id": "com.gucci.app",
                "appstore_app_id": "1534634798",
                "instagram_username": "gucci",
                "tiktok_username": "gucci",
                "youtube_channel_id": "UCo6fjlKg6GuCmEMeqYbGJng",
            },
            {
                "name": "Cartier",
                "website": "https://www.cartier.com/fr-fr",
                "instagram_username": "cartier",
                "tiktok_username": "cartier",
                "youtube_channel_id": "UCu16y62LPCwTknfV5_7Zalg",
            },
            {
                "name": "Saint Laurent",
                "website": "https://www.ysl.com/fr-fr",
                "playstore_app_id": "com.kering.slp.saintlaurent",
                "appstore_app_id": "1623343549",
                "instagram_username": "ysl",
                "tiktok_username": "ysl",
                "youtube_channel_id": "UCPKgOkL5T1HiWpdp8de0U4g",
            },
            {
                "name": "Balenciaga",
                "website": "https://www.balenciaga.com/fr-fr",
                "instagram_username": "balenciaga",
                "tiktok_username": "balenciaga",
                "youtube_channel_id": "UC08-C3TjnbKb6MPnfJd3IVQ",
            },
        ],
    },
    "voyage": {
        "name": "Voyage & Tourisme",
        "competitors": [
            {
                "name": "Booking.com",
                "website": "https://www.booking.com",
                "playstore_app_id": "com.booking",
                "appstore_app_id": "367003839",
                "instagram_username": "bookingcom",
                "tiktok_username": "booking.com",
            },
            {
                "name": "Airbnb",
                "website": "https://www.airbnb.fr",
                "playstore_app_id": "com.airbnb.android",
                "appstore_app_id": "401626263",
                "instagram_username": "airbnb",
                "tiktok_username": "airbnb",
                "youtube_channel_id": "UCCww-R0oM_CQWXerBcNyKKw",
            },
            {
                "name": "SNCF Connect",
                "website": "https://www.sncf-connect.com",
                "playstore_app_id": "com.vsct.vsc.mobile.hor498.android",
                "appstore_app_id": "343889987",
                "instagram_username": "sncfconnect",
                "tiktok_username": "sncf",
                "youtube_channel_id": "UC5vn9mGosXDigQuXXE4I9Pw",
            },
            {
                "name": "Lastminute",
                "website": "https://www.lastminute.com/fr",
                "playstore_app_id": "com.lastminute.mobile.android.production",
                "instagram_username": "lastminute.com",
            },
            {
                "name": "TripAdvisor",
                "website": "https://www.tripadvisor.fr",
                "playstore_app_id": "com.tripadvisor.tripadvisor",
                "appstore_app_id": "284876795",
                "instagram_username": "tripadvisor",
                "tiktok_username": "tripadvisor",
                "youtube_channel_id": "UCS9S86BryT1on_qhDT2Jwig",
            },
            {
                "name": "Expedia",
                "website": "https://www.expedia.fr",
                "playstore_app_id": "com.expedia.bookings",
                "appstore_app_id": "427916203",
                "instagram_username": "expedia",
                "youtube_channel_id": "UCGaOvAFinZ7BCN_FDmw74fQ",
            },
            {
                "name": "Pierre & Vacances",
                "website": "https://www.pierreetvacances.com",
                "playstore_app_id": "com.pierreetvacances.app",
                "appstore_app_id": "1065552056",
                "instagram_username": "pierreetvacances",
            },
            {
                "name": "Club Med",
                "website": "https://www.clubmed.fr",
                "playstore_app_id": "com.clubmed.android.resorts",
                "appstore_app_id": "1666945596",
                "instagram_username": "clubmed",
                "tiktok_username": "clubmed",
            },
        ],
    },
    "bio": {
        "name": "Bio & Naturel",
        "competitors": [
            {
                "name": "Biocoop",
                "website": "https://www.biocoop.fr",
                "playstore_app_id": "com.biocoop.app",
                "instagram_username": "biocoop",
            },
            {
                "name": "Naturalia",
                "website": "https://www.naturalia.fr",
                "playstore_app_id": "com.naturalia.app",
                "instagram_username": "naturalia_magasins_bio",
                "youtube_channel_id": "UCGzDECCw_UGtKOwFH_bhBGQ",
            },
            {
                "name": "La Vie Claire",
                "website": "https://www.lavieclaire.com",
                "instagram_username": "lavieclaire_bio",
                "youtube_channel_id": "UCLgUFrMFrcVOXs6i1A8Y4hA",
            },
            {
                "name": "Bio c' Bon",
                "website": "https://www.bio-c-bon.eu",
                "instagram_username": "biocbon",
            },
            {
                "name": "Marcel & Fils",
                "website": "https://www.marcel-et-fils.com",
                "instagram_username": "marceletfils",
            },
            {
                "name": "L'Eau Vive",
                "website": "https://www.eau-vive.com",
                "instagram_username": "leauvive_bio",
                "youtube_channel_id": "UC7Uq88LrJE2WxYaUM0h4xow",
            },
        ],
    },
    "automobile": {
        "name": "Automobile",
        "competitors": [
            {
                "name": "Renault",
                "website": "https://www.renault.fr",
                "playstore_app_id": "com.renault.myrenault",
                "appstore_app_id": "1440073013",
                "instagram_username": "renault_france",
                "tiktok_username": "renault",
            },
            {
                "name": "Peugeot",
                "website": "https://www.peugeot.fr",
                "playstore_app_id": "com.psa.mypeugeot",
                "instagram_username": "peugeot",
                "tiktok_username": "peugeot",
            },
            {
                "name": "Citroën",
                "website": "https://www.citroen.fr",
                "playstore_app_id": "com.psa.mycitroen",
                "instagram_username": "citroen",
                "tiktok_username": "citroen",
            },
            {
                "name": "Volkswagen",
                "website": "https://www.volkswagen.fr",
                "playstore_app_id": "de.volkswagen.car-net.eu.e-remote",
                "instagram_username": "volkswagen_fr",
            },
            {
                "name": "Toyota",
                "website": "https://www.toyota.fr",
                "playstore_app_id": "com.toyota.oneapp.eu",
                "instagram_username": "toyotafrance",
            },
            {
                "name": "BMW",
                "website": "https://www.bmw.fr",
                "playstore_app_id": "de.bmw.connected.mobile20.row",
                "instagram_username": "bmwfrance",
                "tiktok_username": "bmw",
            },
            {
                "name": "Tesla",
                "website": "https://www.tesla.com/fr_fr",
                "playstore_app_id": "com.teslamotors.tesla",
                "appstore_app_id": "582007913",
                "instagram_username": "teslamotors",
                "tiktok_username": "tesla",
            },
            {
                "name": "Mercedes-Benz",
                "website": "https://www.mercedes-benz.fr",
                "playstore_app_id": "com.daimler.ris.mercedesme.ece",
                "instagram_username": "mercedesbenzfr",
                "youtube_channel_id": "UClj0L8WZrVydk5xKOscI6-A",
            },
        ],
    },
    "fonciere_commerciale": {
        "name": "Foncières Commerciales",
        "competitors": [
            {
                "name": "Carmila",
                "website": "https://www.carmila.com",
                "facebook_page_id": "carmila",
                "youtube_channel_id": "UCLUUZDqGTxyvt-E-XB-ug5Q",
                "playstore_app_id": "com.mallcommapp.carmila",
                "appstore_app_id": "6746479363",
            },
            {
                "name": "Unibail-Rodamco-Westfield",
                "website": "https://www.urw.com",
                "instagram_username": "urw_group",
                "youtube_channel_id": "UCR5zFGwRd-CTenGXXoRC5fA",
            },
            {
                "name": "Klépierre",
                "website": "https://www.klepierre.com",
                "instagram_username": "klepierre",
                "tiktok_username": "klepierre",
                "youtube_channel_id": "UC7Soagoms2jhH37ZHkiN4Jw",
                "playstore_app_id": "com.maxdoro.incontrol.klepierre",
                "appstore_app_id": "1461138637",
            },
            {
                "name": "Altarea",
                "website": "https://www.altarea.com",
                "facebook_page_id": "altarea",
                "youtube_channel_id": "UCxVfc0coJQmSrItTft1rl_g",
            },
            {
                "name": "Mercialys",
                "website": "https://www.mercialys.fr",
                "youtube_channel_id": "UC2hd66QNP0mWEKUHiYTsr5Q",
                "playstore_app_id": "fr.mercialys.lagalerie",
                "appstore_app_id": "987469094",
            },
            {
                "name": "Nhood",
                "website": "https://www.nhood.com",
                "instagram_username": "nhood_corporate",
                "youtube_channel_id": "UCVRAonORkeM5-qOkedJnSCw",
            },
            {
                "name": "Apsys",
                "website": "https://www.apsysgroup.com",
                "instagram_username": "apsys_group",
                "facebook_page_id": "apsys",
            },
            {
                "name": "Hammerson",
                "website": "https://www.hammerson.com",
                "instagram_username": "hammerson_plc",
                "facebook_page_id": "hammersonplc",
                "youtube_channel_id": "UCwU-loR9RJfx_KITuIWPuxg",
            },
            {
                "name": "Wereldhave",
                "website": "https://www.wereldhave.com",
                "youtube_channel_id": "UCCGxZDlcHrorzfi6D9-PYVA",
            },
            {
                "name": "Frey",
                "website": "https://frey.fr",
                "youtube_channel_id": "UCaxeU_i97vgL-pLeBbyiPDg",
            },
            {
                "name": "Patrimoine & Commerce",
                "website": "https://patrimoine-commerce.com",
                "instagram_username": "groupe_duval",
                "facebook_page_id": "groupeduval",
            },
        ],
    },
}


def get_sector_label(sector_code: str) -> str:
    """Retourne le nom complet d'un secteur."""
    return SECTORS.get(sector_code, {}).get("name", sector_code)


def get_competitors_for_sector(sector_code: str) -> list:
    """Retourne la liste des concurrents pré-configurés pour un secteur."""
    return SECTORS.get(sector_code, {}).get("competitors", [])


def list_sectors() -> list:
    """Retourne la liste des secteurs disponibles."""
    return [
        {"code": code, "name": data["name"], "competitors_count": len(data["competitors"])}
        for code, data in SECTORS.items()
    ]


def find_brand_in_sectors(name: str) -> dict | None:
    """Find a brand by name (case-insensitive) across all sectors.
    Returns the competitor dict with sector info, or None."""
    name_lower = name.lower().strip()
    for sector_code, sector_data in SECTORS.items():
        for comp in sector_data.get("competitors", []):
            if comp["name"].lower() == name_lower:
                return {**comp, "sector": sector_code, "sector_name": sector_data["name"]}
    return None
